# Generated by Django 5.1 on 2024-09-03 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loancustomer',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanprovider',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BankPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_term', models.IntegerField(default=1)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_duration', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
