# Generated by Django 4.2.1 on 2024-09-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loancustomer_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loanprovider'),
        ),
    ]
