# Generated by Django 5.1 on 2024-09-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_loan_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loancustomer'),
        ),
    ]
